'use strict';

/* Relay Moth Forest v4.14 — on-canvas WYSIWYG room editor.
 * Editor ownership is deliberately presentation/authoring-only. Runtime gameplay
 * systems continue to consume relay_moth_maps.json through Room as before.
 */
(function(root){
  const TILE=16, GRID_W=40, GRID_H=19, PLAY_H=304, W=640, H=360;
  const clone=v=>JSON.parse(JSON.stringify(v));
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const key=(x,y)=>`${x},${y}`;
  const inside=(x,y)=>x>=0&&x<GRID_W&&y>=0&&y<GRID_H;
  const intersects=(a,b)=>!(a.x1<b.x0||a.x0>b.x1||a.y1<b.y0||a.y0>b.y1);
  const rectFrom=(a,b)=>({x0:Math.min(a.x,b.x),y0:Math.min(a.y,b.y),x1:Math.max(a.x,b.x),y1:Math.max(a.y,b.y)});

  const EDITOR_ITEM_POLICY=Object.freeze({
    blocker:{layer:'terrain',hitPriority:22,select:true,move:true,remove:true,copy:true,property:false,visibility:false},
    tree:{layer:'terrain',hitPriority:23,select:true,move:true,remove:true,copy:true,property:false,visibility:false},
    water:{layer:'terrain',hitPriority:10,select:true,move:true,remove:true,copy:true,property:false,visibility:false},
    path:{layer:'terrain',hitPriority:11,select:true,move:true,remove:true,copy:true,property:false,visibility:false},
    decor:{layer:'decor',hitPriority:34,select:true,move:true,remove:true,copy:true,property:true,visibility:false},
    'procedural-decor':{layer:'decor',hitPriority:35,select:true,move:false,remove:true,copy:false,property:false,visibility:true},
    'suppressed-procedural':{layer:'decor',hitPriority:36,select:true,move:false,remove:false,copy:false,property:false,visibility:true},
    'suppressed-pattern':{layer:'decor',hitPriority:37,select:true,move:false,remove:false,copy:false,property:false,visibility:true},
    'suppressed-decor-tile':{layer:'decor',hitPriority:29,select:true,move:false,remove:false,copy:false,property:false,visibility:true},
    grass:{layer:'decor',hitPriority:31,select:true,move:true,remove:true,copy:true,property:true,visibility:false},
    lamp:{layer:'decor',hitPriority:32,select:true,move:true,remove:true,copy:true,property:true,visibility:false},
    robot:{layer:'decor',hitPriority:33,select:true,move:true,remove:true,copy:true,property:true,visibility:false},
    pattern:{layer:'decor',hitPriority:30,select:true,move:false,remove:true,copy:false,property:false,visibility:true},
    objective:{layer:'gameplay',hitPriority:44,select:true,move:true,remove:false,copy:false,property:true,visibility:true},
    moth:{layer:'gameplay',hitPriority:43,select:true,move:true,remove:true,copy:true,property:true,visibility:false},
    wildlife:{layer:'gameplay',hitPriority:42,select:true,move:true,remove:true,copy:true,property:true,visibility:false},
    mini:{layer:'gameplay',hitPriority:41,select:true,move:true,remove:true,copy:true,property:true,visibility:false},
    structural:{layer:'structural',hitPriority:50,select:false,move:false,remove:false,copy:false,property:false,visibility:false}
  });
  const RelayEditorPolicy=Object.freeze({
    describe(item){
      const p=EDITOR_ITEM_POLICY[item.type]||EDITOR_ITEM_POLICY.structural;
      return {...item,layer:p.layer,hitPriority:p.hitPriority,capabilities:{select:!!p.select,move:!!p.move,remove:!!p.remove,copy:!!p.copy,property:!!p.property,visibility:!!p.visibility}};
    },
    allows(item,scope){
      if(!item)return false;
      const it=item.capabilities?item:this.describe(item),c=it.capabilities;
      if(scope==='right-click')return it.layer==='decor'&&c.remove;
      if(scope==='erase')return (it.layer==='terrain'||it.layer==='decor')&&c.remove;
      if(scope==='select')return (it.layer==='terrain'||it.layer==='decor')&&c.select;
      if(scope==='object')return it.layer==='gameplay'&&c.select;
      if(scope==='move')return c.move;
      if(scope==='remove')return c.remove;
      if(scope==='copy')return c.copy;
      return false;
    },
    pick(items,p,scope){
      const candidates=(items||[]).map(it=>it.capabilities?it:this.describe(it)).filter(it=>this.allows(it,scope)&&p.x>=it.bbox.x0&&p.x<=it.bbox.x1&&p.y>=it.bbox.y0&&p.y<=it.bbox.y1);
      candidates.sort((a,b)=>(a.hitPriority-b.hitPriority)||(a.bbox.y1-b.bbox.y1)||String(a.id).localeCompare(String(b.id)));
      return candidates.length?candidates[candidates.length-1]:null;
    }
  });
  root.RelayEditorPolicy=RelayEditorPolicy;

  class WysiwygEditor{
    constructor(game){
      this.game=game;this.active=false;this.tool='brush';this.category='tiles';this.choice={kind:'path',label:'Path'};
      this.overlay=document.querySelector('#editorOverlay');this.ctx=this.overlay.getContext('2d');
      this.panel=document.querySelector('#wysiwygEditor');this.toolbar=document.querySelector('#editorToolbar');this.palettePanel=document.querySelector('#editorPalette');this.palette=document.querySelector('#editorPaletteGrid');this.search=document.querySelector('#editorPaletteSearch');this.inspectorPanel=document.querySelector('#editorInspector');this.inspector=document.querySelector('#editorInspectorBody');
      this.status=document.querySelector('#editorStatus');this.hover={x:320,y:152};this.pointerDown=false;this.pointerButton=0;this.pointerId=null;this.dragMode=null;this.dragStart=null;this.dragNow=null;this.selection=[];this.clipboard=null;this.history=new Map();this.transaction=null;this.inspectorEdit=null;this.activeRoomKey=this.roomKey();this.paintVisited=new Set();this.showGrid=true;this.showSuppressed=false;this.nextDecorId=1;this._renderQueued=false;
      this.bind();this.buildCategories();this.buildPalette();this.renderOverlay();
    }
    roomKey(){return this.game.room?.key||this.game.storyData.rooms[this.game.state.room]?.key}
    rawRoom(){return this.game.maps.rooms[this.roomKey()]}
    toggle(force=null){const next=force==null?!this.active:!!force;if(next===this.active)return;if(!next&&this.transaction)this.cancelGesture();this.active=next;document.body.classList.toggle('wysiwygEdit',next);if(!next)document.body.classList.remove('wysiwygChromeHidden');this.panel.classList.toggle('hidden',!next);this.overlay.classList.toggle('editorActive',next);if(next){this.syncRoomContext();this.selection=[];this.resetPointerState();this.recountIds();this.buildPalette();this.game.toast('WYSIWYG EDITOR · left paint/select · right remove',1.8)}else{this.selection=[];this.resetPointerState();this.renderOverlay();this.game.toast('Editor closed · gameplay view restored',1.3)}this.updateStatus()}
    bind(){
      this.panel?.querySelectorAll('button').forEach(b=>b.type='button');
      this.overlay.addEventListener('contextmenu',e=>e.preventDefault());
      this.overlay.addEventListener('pointerdown',e=>this.onDown(e));
      this.overlay.addEventListener('pointermove',e=>this.onMove(e));
      this.overlay.addEventListener('pointerup',e=>this.onUp(e));
      this.overlay.addEventListener('pointercancel',e=>this.onCancel(e));
      this.search?.addEventListener('input',()=>this.buildPalette());
      document.querySelectorAll('[data-editor-tool]').forEach(b=>b.addEventListener('click',()=>this.setTool(b.dataset.editorTool)));
      document.querySelectorAll('[data-editor-category]').forEach(b=>b.addEventListener('click',()=>{this.category=b.dataset.editorCategory;const entries=this.entries();if(entries.length)this.choice=entries[0];document.querySelectorAll('[data-editor-category]').forEach(x=>x.classList.toggle('active',x===b));this.buildPalette();this.updateStatus();this.renderOverlay()}));
      document.querySelector('#editorUndo')?.addEventListener('click',()=>this.undoOne());
      document.querySelector('#editorRedo')?.addEventListener('click',()=>this.redoOne());
      document.querySelector('#editorCopy')?.addEventListener('click',()=>this.copySelection());
      document.querySelector('#editorPaste')?.addEventListener('click',()=>this.pasteClipboard());
      document.querySelector('#editorDelete')?.addEventListener('click',()=>this.deleteSelection());
      document.querySelector('#editorObjectiveVisual')?.addEventListener('click',()=>this.toggleObjectiveVisual());
      document.querySelector('#editorRestoreSuppressed')?.addEventListener('click',()=>this.restoreSelectedSuppressed());
      document.querySelector('#editorConvertProcedural')?.addEventListener('click',()=>this.convertProceduralSelection());
      document.querySelector('#editorSuppressed')?.addEventListener('click',e=>{this.showSuppressed=!this.showSuppressed;e.currentTarget.classList.toggle('active',this.showSuppressed);e.currentTarget.textContent=this.showSuppressed?'HIDE SUPPRESSED':'SHOW SUPPRESSED';this.selection=[];this.renderOverlay();this.updateStatus()});
      document.querySelector('#editorGrid')?.addEventListener('click',e=>{this.showGrid=!this.showGrid;e.currentTarget.classList.toggle('active',this.showGrid);this.renderOverlay()});
      document.querySelector('#editorChrome')?.addEventListener('click',()=>this.toggleChrome());
      document.querySelector('#editorSave')?.addEventListener('click',()=>this.saveProject());
      document.querySelector('#editorDownload')?.addEventListener('click',()=>this.downloadMaps());
      document.querySelector('#editorClose')?.addEventListener('click',()=>this.toggle(false));
      window.addEventListener('keydown',e=>this.onKey(e),true);
      window.addEventListener('resize',()=>this.renderOverlay());
      const shield=e=>{if(!this.active)return;e.stopPropagation()};
      for(const ui of [this.toolbar,this.palettePanel,this.inspectorPanel])if(ui){ui.addEventListener('pointerdown',shield);ui.addEventListener('pointerup',shield);ui.addEventListener('pointermove',shield);ui.addEventListener('contextmenu',shield)}
    }
    releasePointer(pointerId=null){const id=pointerId??this.pointerId;try{if(id!=null&&this.overlay.hasPointerCapture?.(id))this.overlay.releasePointerCapture(id)}catch(_){} }
    resetPointerState(pointerId=null){this.releasePointer(pointerId);this.pointerId=null;this.pointerDown=false;this.pointerButton=0;this.dragMode=null;this.dragStart=null;this.dragNow=null;this.moveOriginal=null;this.paintVisited.clear()}
    historyFor(roomKey=this.roomKey()){let h=this.history.get(roomKey);if(!h){h={undo:[],redo:[]};this.history.set(roomKey,h)}return h}
    syncRoomContext(){const current=this.roomKey();if(this.activeRoomKey===current)return false;if(this.transaction)this.cancelTransaction(false);this.selection=[];this.resetPointerState();this.activeRoomKey=current;this.renderOverlay();this.updateStatus();return true}
    beforeRoomChange(){if(this.transaction)this.cancelTransaction(false);this.selection=[];this.resetPointerState();this.activeRoomKey=null;this.renderOverlay();this.updateStatus()}
    onRoomChanged(){this.syncRoomContext()}
    cancelGesture(pointerId=null){if(this.transaction)this.cancelTransaction();else{this.selection=[];this.renderOverlay();this.updateStatus()}this.resetPointerState(pointerId)}
    toggleChrome(){document.body.classList.toggle('wysiwygChromeHidden');const b=document.querySelector('#editorChrome');if(b)b.textContent=document.body.classList.contains('wysiwygChromeHidden')?'SHOW UI':'HIDE UI';this.renderOverlay()}
    onKey(e){if(!this.active)return;if(e.key==='F2'||e.key==='F11')return;e.stopImmediatePropagation();const target=e.target?.tagName;if(target==='INPUT'||target==='TEXTAREA'||target==='SELECT')return;if(e.key==='Tab'){e.preventDefault();this.toggleChrome();return}
      if(e.key==='Escape'){e.preventDefault();if(this.pointerDown||this.dragMode||this.transaction)this.cancelGesture();else this.toggle(false);return}
      const k=e.key.toLowerCase();if((e.ctrlKey||e.metaKey)&&k==='z'){e.preventDefault();e.shiftKey?this.redoOne():this.undoOne();return}if((e.ctrlKey||e.metaKey)&&k==='y'){e.preventDefault();this.redoOne();return}if((e.ctrlKey||e.metaKey)&&k==='c'){e.preventDefault();this.copySelection();return}if((e.ctrlKey||e.metaKey)&&k==='v'){e.preventDefault();this.pasteClipboard();return}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();this.deleteSelection();return}
      if(k==='b'){this.setTool('brush');e.preventDefault()}else if(k==='s'){this.setTool('select');e.preventDefault()}else if(k==='o'){this.setTool('object');e.preventDefault()}else if(k==='e'){this.setTool('erase');e.preventDefault()}else if(k==='v'){this.setTool('move');e.preventDefault()}
    }
    setTool(tool){this.tool=tool;document.querySelectorAll('[data-editor-tool]').forEach(b=>b.classList.toggle('active',b.dataset.editorTool===tool));this.overlay.style.cursor=(tool==='select'||tool==='object')?'crosshair':tool==='move'?'move':tool==='erase'?'not-allowed':'crosshair';this.updateStatus();this.renderOverlay()}
    logical(ev){const r=this.overlay.getBoundingClientRect();return{x:clamp((ev.clientX-r.left)/r.width*W,0,W-.001),y:clamp((ev.clientY-r.top)/r.height*H,0,H-.001)}}
    tileAt(p){return[clamp(Math.floor(p.x/TILE),0,GRID_W-1),clamp(Math.floor(p.y/TILE),0,GRID_H-1)]}
    beginTransaction(label){this.syncRoomContext();if(this.transaction)return false;const roomKey=this.roomKey();this.transaction={roomKey,label,before:clone(this.game.maps.rooms[roomKey])};return true}
    commitTransaction(){if(!this.transaction)return false;const t=this.transaction;if(this.roomKey()!==t.roomKey){this.cancelTransaction(false);return false}const after=clone(this.game.maps.rooms[t.roomKey]);if(JSON.stringify(after)!==JSON.stringify(t.before)){const h=this.historyFor(t.roomKey);h.undo.push({roomKey:t.roomKey,label:t.label,before:clone(t.before),after});if(h.undo.length>48)h.undo.shift();h.redo.length=0}this.transaction=null;this.updateStatus();return true}
    cancelTransaction(rebuild=true){if(!this.transaction)return false;const t=this.transaction;this.game.maps.rooms[t.roomKey]=clone(t.before);this.transaction=null;this.selection=[];if(rebuild&&this.roomKey()===t.roomKey)this.rebuildRoom();else{this.renderOverlay();this.updateStatus()}return true}
    undoOne(){this.syncRoomContext();const roomKey=this.roomKey(),h=this.historyFor(roomKey);if(!h.undo.length)return false;const u=h.undo.pop();this.game.maps.rooms[u.roomKey]=clone(u.before);h.redo.push(u);this.selection=[];this.rebuildRoom();this.game.toast('Editor undo · '+u.label,1.1);this.updateStatus();return true}
    redoOne(){this.syncRoomContext();const roomKey=this.roomKey(),h=this.historyFor(roomKey);if(!h.redo.length)return false;const u=h.redo.pop();this.game.maps.rooms[u.roomKey]=clone(u.after);h.undo.push(u);if(h.undo.length>48)h.undo.shift();this.selection=[];this.rebuildRoom();this.game.toast('Editor redo · '+u.label,1.1);this.updateStatus();return true}
    recountIds(){let n=1;for(const d of this.rawRoom()?.editor_decor||[]){const m=String(d.editor_id||'').match(/(\d+)$/);if(m)n=Math.max(n,Number(m[1])+1)}this.nextDecorId=n}
    buildCategories(){document.querySelectorAll('[data-editor-category]').forEach(b=>b.classList.toggle('active',b.dataset.editorCategory===this.category))}
    entries(){const art=this.game.art,roles=art.roles||{},arr=[];
      if(this.category==='tiles')return[
        {kind:'path',label:'Path tile',swatch:'#b18b58'},{kind:'water',label:'Water tile',swatch:'#277a9a'},{kind:'solid',label:'Solid blocker',sprite:(roles.blocker_variants||roles.blockers||[])[0]},{kind:'clear',label:'Clear tile',swatch:'#293a38'}];
      if(this.category==='blockers')for(const s of roles.blocker_variants||roles.blockers||[])arr.push({kind:'blocker',label:s,sprite:s});
      if(this.category==='trees')for(const s of roles.tree_blockers||[])arr.push({kind:'tree',label:s,sprite:s});
      if(this.category==='decor')for(const s of [...new Set([...(roles.decor_plants||[]),...(roles.foliage_v401_all||[])])])arr.push({kind:'decor',label:s,sprite:s});
      if(this.category==='grass')return[
        {kind:'grass',label:'Grass · light',radius:17,density:.85,swatch:'#377f61'},
        {kind:'grass',label:'Grass · normal',radius:22,density:1.25,swatch:'#3da875'},
        {kind:'grass',label:'Grass · dense',radius:27,density:1.75,swatch:'#59d892'},
        {kind:'grass',label:'Grass · lush',radius:32,density:2.25,swatch:'#78f4ac'}];
      if(this.category==='lamps')for(const s of (roles.lamps||[]).filter(x=>x.startsWith('lamp_')||x.startsWith('lantern_')))arr.push({kind:'lamp',label:s,sprite:s});
      if(this.category==='robots')for(const v of roles.decor_robots||Object.keys(roles.robot_variants||{})){const sprite=roles.robot_variants?.[v]?.idle;arr.push({kind:'robot',label:v,variant:v,sprite})}
      if(this.category==='moths')for(let i=0;i<(roles.moths||[]).length;i++)arr.push({kind:'moth',label:`Relay moth ${i+1}`,variant:i,sprite:roles.moths[i],colour_index:55+i*34});
      if(this.category==='wildlife')for(const [kind,frames] of Object.entries(roles.creatures||{}))arr.push({kind:'wildlife',label:kind.replaceAll('_',' '),wildlifeKind:kind,sprite:frames.idle,count:1});
      if(this.category==='mini')for(const [variant,frames] of Object.entries(roles.mini_robots||{}))arr.push({kind:'mini',label:`mini ${variant}`,variant,sprite:frames.idle,count:2});
      if(this.category==='ambient')for(const [label,sprite,alpha,scale] of [['Moon + star wave','moon_star_wave',.50,.90],['Moon','guide_moon',.55,.85],['Star swirl','swirl_large',.40,.75]])if(art.regions[sprite])arr.push({kind:'ambient',label,sprite,alpha,scale});
      return arr;
    }
    buildPalette(){if(!this.palette)return;const q=(this.search?.value||'').trim().toLowerCase(),entries=this.entries().filter(e=>!q||e.label.toLowerCase().includes(q));this.palette.innerHTML='';for(const e of entries){const b=document.createElement('button');b.type='button';b.className='editorPaletteItem';b.title=e.label;b.dataset.kind=e.kind;const cv=document.createElement('canvas');cv.width=54;cv.height=48;const x=cv.getContext('2d');x.clearRect(0,0,54,48);if(e.sprite&&this.game.art.regions[e.sprite]){const r=this.game.art.region(e.sprite),scale=Math.min(48/r[2],42/r[3],1),dw=r[2]*scale,dh=r[3]*scale;x.imageSmoothingEnabled=true;x.drawImage(this.game.art.img,r[0],r[1],r[2],r[3],27-dw/2,47-dh,dw,dh)}else{x.fillStyle=e.swatch||'#6b8792';x.fillRect(9,9,36,30);x.strokeStyle='#dff';x.strokeRect(9.5,9.5,35,29)}const span=document.createElement('span');span.textContent=e.label;b.append(cv,span);b.onclick=()=>{this.choice=e;this.setTool('brush');this.palette.querySelectorAll('.editorPaletteItem').forEach(z=>z.classList.toggle('active',z===b));this.updateStatus();this.renderOverlay()};this.palette.append(b)}if(entries.length)this.palette.firstElementChild?.classList.toggle('active',this.choice?.label===entries[0].label&&this.choice?.kind===entries[0].kind)}
    onDown(e){if(!this.active)return;this.syncRoomContext();e.preventDefault();e.stopPropagation();const p=this.logical(e);if(p.y>=PLAY_H||![0,2].includes(e.button)){this.releasePointer(e.pointerId);return}this.overlay.setPointerCapture?.(e.pointerId);this.pointerId=e.pointerId;this.hover=p;this.pointerDown=true;this.pointerButton=e.button;this.dragStart=p;this.dragNow=p;this.paintVisited.clear();
      if(e.button===2){this.beginTransaction('remove decoration');this.dragMode='eraseDecor';this.eraseAt(p,'right-click');return}
      if(this.tool==='erase'){this.beginTransaction('erase');this.dragMode='erase';this.eraseAt(p,'erase');return}
      if(e.button!==0)return;
      if(this.tool==='brush'){this.beginTransaction('paint');this.dragMode='paint';this.paintAt(p);return}
      const hit=this.tool==='move'?this.hitSelectedAt(p):this.hitAt(p,this.tool==='object'?'object':'select');
      const dragSelection=hit&&this.selection.some(s=>this.sameRef(s,hit))&&this.selection.length&&this.selection.every(s=>RelayEditorPolicy.allows(s,'move'));
      if((this.tool==='move'&&hit)||((this.tool==='select'||this.tool==='object')&&dragSelection)){this.beginTransaction('move selection');this.dragMode='move';this.moveOriginal=this.captureSelectionState();this.renderOverlay();return}
      if(this.tool==='object'){if(hit&&!e.shiftKey){this.selection=[hit];this.dragMode='clickSelect'}else if(hit&&e.shiftKey){const ix=this.selection.findIndex(s=>this.sameRef(s,hit));if(ix>=0)this.selection.splice(ix,1);else this.selection.push(hit);this.dragMode='clickSelect'}else{if(!e.shiftKey)this.selection=[];this.dragMode='objectSelectBox'}this.renderOverlay();return}
      if(this.tool==='select'){if(hit&&!e.shiftKey){this.selection=[hit];this.dragMode='clickSelect'}else if(hit&&e.shiftKey){const ix=this.selection.findIndex(s=>this.sameRef(s,hit));if(ix>=0)this.selection.splice(ix,1);else this.selection.push(hit);this.dragMode='clickSelect'}else{if(!e.shiftKey)this.selection=[];this.dragMode='selectBox'}this.renderOverlay()}
    }
    onMove(e){if(!this.active)return;this.syncRoomContext();e.stopPropagation();let p=this.logical(e);if(this.pointerDown&&p.y>=PLAY_H)p={x:p.x,y:PLAY_H-.001};this.hover=p;this.dragNow=p;if(!this.pointerDown){this.renderOverlay();return}if(this.dragMode==='paint')this.paintAt(p);else if(this.dragMode==='erase')this.eraseAt(p,'erase');else if(this.dragMode==='eraseDecor')this.eraseAt(p,'right-click');else if(this.dragMode==='move')this.previewMove(p);else this.renderOverlay()}
    onUp(e){if(!this.active){this.releasePointer(e.pointerId);return}this.syncRoomContext();e.stopPropagation();const p=this.logical(e);this.hover=p;this.dragNow=p;if((this.dragMode==='selectBox'||this.dragMode==='objectSelectBox')&&this.dragStart){const r=rectFrom(this.dragStart,p),scope=this.dragMode==='objectSelectBox'?'object':'select';this.selection=this.collectItems().filter(it=>RelayEditorPolicy.allows(it,scope)&&intersects(it.bbox,r))}else if(this.dragMode==='move'){this.applyMove(p);this.commitTransaction()}else if(this.dragMode==='paint'||this.dragMode==='erase'||this.dragMode==='eraseDecor')this.commitTransaction();this.resetPointerState(e.pointerId);this.renderOverlay();this.updateStatus()}
    onCancel(e){if(!this.active){this.releasePointer(e.pointerId);return}e.preventDefault?.();e.stopPropagation?.();this.cancelGesture(e.pointerId)}
    paintAt(p){const c=this.choice;if(!c)return;const [tx,ty]=this.tileAt(p),visit=(c.kind==='decor'||c.kind==='grass')?`${c.kind}:${Math.round(p.x/4)},${Math.round(p.y/4)}`:`${c.kind}:${tx},${ty}`;if(this.paintVisited.has(visit))return;this.paintVisited.add(visit);if(c.kind==='decor'||c.kind==='grass'){if(this.dragStart&&Math.hypot(p.x-this.dragStart.x,p.y-this.dragStart.y)<3&&this.paintVisited.size>1)return}
      const r=this.rawRoom();r.decor_exclusions=(r.decor_exclusions||[]).filter(q=>(Array.isArray(q)?key(q[0],q[1]):String(q))!==key(tx,ty));if(c.kind==='path'||c.kind==='water'||c.kind==='solid'||c.kind==='clear'||c.kind==='blocker'||c.kind==='tree')this.placeTile(c,tx,ty);else if(c.kind==='decor'||c.kind==='ambient'){r.editor_decor=r.editor_decor||[];r.editor_decor.push({editor_id:`decor_${this.nextDecorId++}`,x:Math.round(p.x),y:Math.min(PLAY_H,Math.round(p.y)),sprite:c.sprite,scale:c.scale??1,alpha:c.alpha??1,flip:false,element:c.kind==='ambient'?'stars':undefined})}else if(c.kind==='grass'){r.grass_clumps=r.grass_clumps||[];r.grass_clumps.push({x:Math.round(p.x*100)/100,y:Math.min(PLAY_H,Math.round(p.y*100)/100),radius:c.radius,density:c.density,seed:(Date.now()+this.paintVisited.size*7919)>>>0})}else if(c.kind==='lamp'){this.replaceByTile(r.decor_lamps=r.decor_lamps||[],tx,ty,{tile:[tx,ty],lamp:c.sprite})}else if(c.kind==='robot'){this.replaceByTile(r.decor_robots=r.decor_robots||[],tx,ty,{tile:[tx,ty],variant:c.variant})}else if(c.kind==='moth'){r.moth_pickups=r.moth_pickups||[];r.moth_pickups.push({id:this.nextPersistentId('moth','editor_moth'),tile:[tx,ty],variant:c.variant||0,colour_index:c.colour_index??210})}else if(c.kind==='wildlife'){r.creature_groups=r.creature_groups||[];r.creature_groups.push({id:this.nextPersistentId('wildlife',`editor_${c.wildlifeKind}`),kind:c.wildlifeKind,count:c.count||1,spawn:[tx,ty],seed:(Date.now()+this.nextDecorId*3571)>>>0})}else if(c.kind==='mini'){r.mini_robot_groups=r.mini_robot_groups||[];r.mini_robot_groups.push({id:this.nextPersistentId('mini',`editor_mini_${c.variant}`),variant:c.variant,count:c.count||1,spawn:[tx,ty],seed:(Date.now()+this.nextDecorId*4111)>>>0})}this.rebuildRoom()}
    nextPersistentId(type,prefix){return RelayEditorIdentity.allocate(this.game.maps,type,prefix)}
    replaceByTile(arr,tx,ty,obj){for(let i=arr.length-1;i>=0;i--)if(arr[i].tile?.[0]===tx&&arr[i].tile?.[1]===ty)arr.splice(i,1);arr.push(obj)}
    placeTile(c,tx,ty){if(!inside(tx,ty))return;const r=this.rawRoom(),k=key(tx,ty);for(const name of ['walls','water','path_cells'])r[name]=(r[name]||[]).filter(q=>key(q[0],q[1])!==k);if(r.blocker_styles)delete r.blocker_styles[k];r.large_trees=(r.large_trees||[]).filter(t=>key(t.tile?.[0],t.tile?.[1])!==k);
      if(c.kind==='clear')return;if(c.kind==='path'){r.path_cells.push([tx,ty]);return}if(c.kind==='water'){r.water.push([tx,ty]);return}r.walls.push([tx,ty]);r.blocker_styles=r.blocker_styles||{};const sprite=c.sprite||(this.game.art.roles.blocker_variants||[])[0];if(c.kind==='tree'){r.blocker_styles[k]={sprite,kind:'tree',lut:'blockers',scale:1,canopy:true};r.large_trees.push({tile:[tx,ty],sprite})}else r.blocker_styles[k]={sprite,kind:'blocker',lut:'blockers',scale:1}}
    eraseAt(p,scope='erase'){const hit=this.hitAt(p,scope);if(hit){this.removeRef(hit);this.selection=this.selection.filter(s=>!this.sameRef(s,hit));this.rebuildRoom();return}if(scope==='right-click'){const protectedHit=this.hitAt(p,'object');if(protectedHit?.type==='objective'){this.game.toast('Objective is protected; use HIDE VISUAL.',1.8);return}const [tx,ty]=this.tileAt(p),r=this.rawRoom(),k=key(tx,ty);r.decor_exclusions=r.decor_exclusions||[];if(!r.decor_exclusions.some(q=>(Array.isArray(q)?key(q[0],q[1]):String(q))===k)){r.decor_exclusions.push([tx,ty]);this.rebuildRoom()}}}
    sameRef(a,b){return a&&b&&a.type===b.type&&a.id===b.id}
    collectItems(){const r=this.rawRoom(),out=[],wallSet=new Set((r.walls||[]).map(q=>key(q[0],q[1]))),treeMap=new Map((r.large_trees||[]).map((x,i)=>[key(x.tile?.[0],x.tile?.[1]),i]));for(const q of r.walls||[]){const k=key(q[0],q[1]),style=r.blocker_styles?.[k]||{},ti=treeMap.get(k);if(ti!=null){const t=r.large_trees[ti],bbox=this.spriteBBox(t.sprite,q[0]*TILE+TILE/2,q[1]*TILE+TILE+2,true);out.push({type:'tree',id:k,tile:[...q],index:ti,bbox})}else{const sprite=style.sprite||(this.game.art.roles.blocker_variants||[])[0],bbox=this.spriteBBox(sprite,q[0]*TILE+TILE/2,q[1]*TILE+TILE+2,true);out.push({type:'blocker',id:k,tile:[...q],bbox})}}
      for(const q of r.water||[])if(!wallSet.has(key(q[0],q[1])))out.push({type:'water',id:key(q[0],q[1]),tile:[...q],bbox:{x0:q[0]*TILE,y0:q[1]*TILE,x1:(q[0]+1)*TILE,y1:(q[1]+1)*TILE}});
      for(const q of r.path_cells||[])if(!wallSet.has(key(q[0],q[1])))out.push({type:'path',id:key(q[0],q[1]),tile:[...q],bbox:{x0:q[0]*TILE,y0:q[1]*TILE,x1:(q[0]+1)*TILE,y1:(q[1]+1)*TILE}});
      (r.editor_decor||[]).forEach((d,i)=>out.push({type:'decor',id:d.editor_id||`decor:${i}`,index:i,obj:d,bbox:this.spriteBBox(d.sprite,d.x,d.y,true,this.game.painter.spriteScale(d.sprite,d.scale??1),Number(d.rot)||0)}));
      for(const d of RelayProceduralDecor.enumerate(this.game.room,this.game.art.roles))out.push({type:'procedural-decor',id:d.id,obj:d,tile:[...d.tile],bbox:this.spriteBBox(d.sprite,d.x,d.y,true,this.game.painter.spriteScale(d.sprite,d.scale??1),0)});
      if(this.showSuppressed){const covered=new Set();for(const d of RelayProceduralDecor.enumerate(this.game.room,this.game.art.roles,{includeSuppressed:true}).filter(d=>d.suppressed)){covered.add(key(d.tile[0],d.tile[1]));out.push({type:'suppressed-procedural',id:d.id,obj:d,tile:[...d.tile],suppressed:true,bbox:this.spriteBBox(d.sprite,d.x,d.y,true,this.game.painter.spriteScale(d.sprite,d.scale??1),0)})}for(const q of r.decor_exclusions||[]){const tile=Array.isArray(q)?q:String(q).split(',').map(Number),k=key(tile[0],tile[1]);if(covered.has(k))continue;out.push({type:'suppressed-decor-tile',id:`decor-exclusion:${k}`,tile:[tile[0],tile[1]],suppressed:true,bbox:{x0:tile[0]*TILE,y0:tile[1]*TILE,x1:(tile[0]+1)*TILE,y1:(tile[1]+1)*TILE}})}}
      (r.grass_clumps||[]).forEach((g,i)=>out.push({type:'grass',id:`grass:${i}`,index:i,obj:g,bbox:{x0:g.x-g.radius,y0:g.y-g.radius*.7,x1:g.x+g.radius,y1:g.y+g.radius*.7}}));
      (r.decor_lamps||[]).forEach((d,i)=>{const [tx,ty]=d.tile||[0,0],x=tx*TILE+TILE/2,y=ty*TILE+TILE/2;out.push({type:'lamp',id:`lamp:${i}`,index:i,obj:d,tile:[tx,ty],bbox:{x0:x-10,y0:y-48,x1:x+10,y1:y+13}})});
      (r.decor_robots||[]).forEach((d,i)=>{const [tx,ty]=d.tile||[0,0],x=tx*TILE+TILE/2,y=ty*TILE+TILE/2+10,s=this.game.art.roles.robot_variants?.[d.variant||'cream']?.idle;out.push({type:'robot',id:d.id?String(d.id):`robot:${i}`,index:i,obj:d,tile:[tx,ty],bbox:this.spriteBBox(s,x,y,true,.84)})});
      {const hiddenObjectives=new Set((r.object_fx_hidden||[]).map(String));for(const obj of this.game.room.spec.objects||[]){const tile=r.objects?.[obj.object_id];if(!tile)continue;const [x,y]=this.game.room.center(tile),sprite=this.game.art.roles.objective?.[obj.kind]||'orb_cyan',bb=this.spriteBBox(sprite,x,y+10,true,1);bb.y0=Math.min(bb.y0,y-18);bb.x0=Math.min(bb.x0,x-14);bb.x1=Math.max(bb.x1,x+14);bb.y1=Math.max(bb.y1,y+14);out.push({type:'objective',id:obj.object_id,obj,tile:[...tile],hiddenVisual:hiddenObjectives.has(String(obj.object_id)),bbox:bb})}}
      (r.moth_pickups||[]).forEach((m,i)=>{const [tx,ty]=m.tile||[0,0],[x,y]=this.game.room.center([tx,ty]),sprite=(this.game.art.roles.moths||[])[(m.variant||0)%Math.max(1,(this.game.art.roles.moths||[]).length)];out.push({type:'moth',id:m.id||`moth:${i}`,index:i,obj:m,tile:[tx,ty],bbox:this.spriteBBox(sprite,x,y,false,.48)})});
      (r.creature_groups||[]).forEach((cg,i)=>{const live=(this.game.creatures?.units||[]).filter(u=>String(u.id||'').startsWith(String(cg.id)+'_')),frames=this.game.art.roles.creatures?.[cg.kind]||{},sprite=frames.idle,spawn=[...(cg.spawn||[0,0])],[sx,sy]=this.game.room.center(spawn),scale=(cg.kind==='pixie'||cg.kind==='mushroom_pixie')?1.62:1.755,boxes=(live.length?live.map(u=>this.spriteBBox(sprite,u.x,u.y,false,scale)):[this.spriteBBox(sprite,sx,sy,false,scale)]);boxes.push({x0:sx-7,y0:sy-7,x1:sx+7,y1:sy+7});const bbox={x0:Math.min(...boxes.map(b=>b.x0)),y0:Math.min(...boxes.map(b=>b.y0)),x1:Math.max(...boxes.map(b=>b.x1)),y1:Math.max(...boxes.map(b=>b.y1))};out.push({type:'wildlife',id:String(cg.id||`wildlife:${i}`),index:i,obj:cg,tile:spawn,bbox})});
      (r.mini_robot_groups||[]).forEach((mg,i)=>{const [x,y]=this.game.room.center(mg.spawn||[0,0]),sprite=this.game.art.roles.mini_robots?.[mg.variant||'teal']?.idle;out.push({type:'mini',id:String(mg.id||`mini:${i}`),index:i,obj:mg,tile:[...(mg.spawn||[0,0])],bbox:this.spriteBBox(sprite,x,y,false,1.52)})});
      out.push(...this.patternItems(r,this.showSuppressed));return out.map(it=>RelayEditorPolicy.describe(it))}
    patternItems(r,includeSuppressed=false){const out=[],described=new Set(),p=this.game.room.spec.pattern||this.game.room.spec.key,cx=W/2,cy=PLAY_H*.54,hidden=new Set((r.pattern_exclusions||[]).map(String)),add=(id,sprite,x,y,scale=1,label=id)=>{const suppressed=hidden.has(id);if((suppressed&&!includeSuppressed)||!this.game.art.regions[sprite])return;described.add(String(id));out.push({type:suppressed?'suppressed-pattern':'pattern',id,obj:{label,sprite,x,y,scale,suppressed},suppressed,bbox:this.spriteBBox(sprite,x,y,false,scale)})};if(p==='nest')add('nest:swirl','swirl_large',cx,cy+25,1.3,'Moon / star swirl');if(p==='lane')[[0,145,'candelabra_small'],[1,320,'candelabra_wide'],[2,495,'candelabra_small']].forEach(([i,x,s])=>add(`lane:lamp:${i}`,s,x,125,1,`Lane lamp ${i+1}`));if(p==='home')add('home:orb',(this.game.art.roles.objective?.beacon==='orb_green')?'orb_magenta':'orb_green',cx+82,cy+29,1,'Home orb');if(p==='orchard')for(let i=0;i<4;i++)add(`orchard:lamp:${i}`,'candelabra_small',150+i*115,103,1,`Orchard lamp ${i+1}`);if(p==='battery'){const orbs=['orb_magenta','orb_green','orb_orange','orb_cyan','orb_purple'];for(let i=0;i<orbs.length;i++){const a=i/orbs.length*TAU-.5,rr=82;add(`battery:orb:${i}`,orbs[i],cx+Math.cos(a)*rr,cy+Math.sin(a)*rr*.52,1,`Battery orb ${i+1}`)}}if(p==='dawn'){add('dawn:orb','orb_orange',cx,150,1.25,'Dawn orb');if(this.game.state.roomComplete(this.game.room.spec))add('dawn:swirl','swirl_large',cx,cy+20,1.45,'Dawn star swirl')}if(p==='ferns'){const names=this.game.art.roles.decor_plants||[];for(let i=0;i<10;i++){const a=i/10*TAU,rr=75,n=names[i%Math.max(1,names.length)];if(n)add(`ferns:${i}`,n,cx+Math.cos(a)*rr,cy+Math.sin(a)*rr*.56+22,1,`Fern ring ${i+1}`)}}if(p==='garden'){const names=['bush_yellow','bush_blue','bush_pair','flower_pink','flower_blue','flower_bush'];for(let i=0;i<24;i++){const seed=hash32(i,this.game.room.index,440),x=42+(seed%555),y=72+((seed>>>8)%175),n=names[i%names.length];if(this.game.art.regions[n])add(`garden:${i}`,n,x,y+18,1,`Garden decor ${i+1}`)}}if(includeSuppressed)for(const id of hidden)if(!described.has(id))out.push({type:'suppressed-pattern',id,obj:{label:id,sprite:null,x:cx,y:cy,scale:1,suppressed:true},suppressed:true,bbox:{x0:cx-8,y0:cy-8,x1:cx+8,y1:cy+8}});return out}
    spriteBBox(sprite,x,y,bottom=true,scale=1,rot=0){if(!sprite||!this.game.art.regions[sprite])return{x0:x-8,y0:y-16,x1:x+8,y1:y};const [w,h]=this.game.art.worldSize(sprite,scale),top=bottom?-h:-h/2,co=Math.cos(rot),si=Math.sin(rot),pts=[[-w/2,top],[w/2,top],[-w/2,top+h],[w/2,top+h]].map(([px,py])=>[x+co*px-si*py,y+si*px+co*py]);return{x0:Math.min(...pts.map(p=>p[0])),y0:Math.min(...pts.map(p=>p[1])),x1:Math.max(...pts.map(p=>p[0])),y1:Math.max(...pts.map(p=>p[1]))}}
    hitAt(p,scope='select',items=null){return RelayEditorPolicy.pick(items||this.collectItems(),p,scope)}
    hitSelectedAt(p){if(!this.selection.length||!this.selection.every(it=>RelayEditorPolicy.allows(it,'move')))return null;return RelayEditorPolicy.pick(this.selection,p,'move')}
    removeRef(ref){const r=this.rawRoom();if(ref.type==='blocker'||ref.type==='tree'||ref.type==='water'||ref.type==='path'){const [tx,ty]=ref.tile,k=key(tx,ty);for(const n of ['walls','water','path_cells'])r[n]=(r[n]||[]).filter(q=>key(q[0],q[1])!==k);if(r.blocker_styles)delete r.blocker_styles[k];r.large_trees=(r.large_trees||[]).filter(t=>key(t.tile?.[0],t.tile?.[1])!==k);return}if(ref.type==='decor'){const a=r.editor_decor||[],i=ref.obj?a.indexOf(ref.obj):-1;if(i>=0)a.splice(i,1);else r.editor_decor=a.filter((d,j)=>(d.editor_id||`decor:${j}`)!==ref.id)}else if(ref.type==='procedural-decor'){RelayProceduralDecor.suppress(r,ref.obj||ref)}else if(ref.type==='grass'){const a=r.grass_clumps||[],i=ref.obj?a.indexOf(ref.obj):-1;if(i>=0)a.splice(i,1)}else if(ref.type==='lamp'){const a=r.decor_lamps||[],i=ref.obj?a.indexOf(ref.obj):-1;if(i>=0)a.splice(i,1)}else if(ref.type==='robot'){const a=r.decor_robots||[],i=ref.obj?a.indexOf(ref.obj):-1;if(i>=0)a.splice(i,1)}else if(ref.type==='moth'){const a=r.moth_pickups||[],i=ref.obj?a.indexOf(ref.obj):-1;if(i>=0)a.splice(i,1)}else if(ref.type==='wildlife'){const a=r.creature_groups||[],i=ref.obj?a.indexOf(ref.obj):-1;if(i>=0)a.splice(i,1)}else if(ref.type==='mini'){const a=r.mini_robot_groups||[],i=ref.obj?a.indexOf(ref.obj):-1;if(i>=0)a.splice(i,1)}else if(ref.type==='pattern'){r.pattern_exclusions=r.pattern_exclusions||[];if(!r.pattern_exclusions.includes(ref.id))r.pattern_exclusions.push(ref.id)}else if(ref.type==='objective'){this.game.toast('Objectives are protected; use HIDE VISUAL.',1.8)}}
    deleteSelection(){if(!this.selection.length)return;const removable=this.selection.filter(s=>RelayEditorPolicy.allows(s,'remove'));if(!removable.length){this.game.toast(this.selection.some(s=>s.type==='objective')?'Objectives are not deleted; use HIDE VISUAL.':'Selection is protected from generic delete.',1.8);return}this.beginTransaction('delete selection');for(const s of [...removable].reverse())this.removeRef(s);this.selection=this.selection.filter(s=>!removable.some(r=>this.sameRef(s,r)));this.rebuildRoom();this.commitTransaction()}
    captureSelectionState(){const r=this.rawRoom(),states=[];for(const ref of this.selection){if(ref.type==='decor'){const d=(r.editor_decor||[]).find((d,i)=>(d.editor_id||`decor:${i}`)===ref.id);if(d)states.push({ref,kind:'pixel',x:d.x,y:d.y})}else if(ref.type==='grass'){const g=ref.obj||(r.grass_clumps||[])[ref.index];if(g)states.push({ref,kind:'pixel',x:g.x,y:g.y})}else if(['lamp','robot','blocker','tree','water','path','objective','moth','wildlife','mini'].includes(ref.type)){states.push({ref,kind:'tile',tx:ref.tile[0],ty:ref.tile[1]})}else if(ref.type==='pattern'){states.push({ref,kind:'pixel',x:(ref.bbox.x0+ref.bbox.x1)/2,y:(ref.bbox.y0+ref.bbox.y1)/2})}}return states}
    previewMove(){this.renderOverlay()}
    applyMove(p){if(!this.moveOriginal||!this.dragStart)return;const dx=p.x-this.dragStart.x,dy=p.y-this.dragStart.y,tdx=Math.round(dx/TILE),tdy=Math.round(dy/TILE),r=this.rawRoom();if(this.selection.some(s=>s.type==='pattern')){this.game.toast('Procedural ambient objects can be removed or replaced, but not moved directly.',1.7);return}const copies=this.copySelectionData(this.selection);for(const ref of [...this.selection].reverse()){if(ref.type==='objective')continue;this.removeRef(ref)}for(const c of copies){if(c.type==='objective'){r.objects[c.data.object_id]=[clamp(c.tx+tdx,0,GRID_W-1),clamp(c.ty+tdy,0,GRID_H-1)]}else this.pasteDataItem(c,c.kind==='pixel'?dx:tdx,c.kind==='pixel'?dy:tdy,true)}this.rebuildRoom()}
    copySelectionData(refs){const r=this.rawRoom(),out=[];for(const ref of refs){if(ref.type==='decor'){const d=(r.editor_decor||[]).find((d,i)=>(d.editor_id||`decor:${i}`)===ref.id);if(d)out.push({type:'decor',kind:'pixel',data:clone(d),x:d.x,y:d.y})}else if(ref.type==='grass'){const g=ref.obj||(r.grass_clumps||[])[ref.index];if(g)out.push({type:'grass',kind:'pixel',data:clone(g),x:g.x,y:g.y})}else if(ref.type==='lamp'){const d=ref.obj||(r.decor_lamps||[])[ref.index];if(d)out.push({type:'lamp',kind:'tile',data:clone(d),tx:d.tile[0],ty:d.tile[1]})}else if(ref.type==='robot'){const d=ref.obj||(r.decor_robots||[])[ref.index];if(d)out.push({type:'robot',kind:'tile',data:clone(d),tx:d.tile[0],ty:d.tile[1]})}else if(ref.type==='objective'){const tile=r.objects?.[ref.id];if(tile)out.push({type:'objective',kind:'tile',data:{object_id:ref.id},tx:tile[0],ty:tile[1]})}else if(ref.type==='moth'){const d=ref.obj||(r.moth_pickups||[])[ref.index];if(d)out.push({type:'moth',kind:'tile',data:clone(d),tx:d.tile[0],ty:d.tile[1]})}else if(ref.type==='wildlife'){const d=ref.obj||(r.creature_groups||[])[ref.index];if(d)out.push({type:'wildlife',kind:'tile',data:clone(d),tx:d.spawn[0],ty:d.spawn[1]})}else if(ref.type==='mini'){const d=ref.obj||(r.mini_robot_groups||[])[ref.index];if(d)out.push({type:'mini',kind:'tile',data:clone(d),tx:d.spawn[0],ty:d.spawn[1]})}else if(ref.type==='tree'){const style=clone(r.blocker_styles?.[ref.id]||{}),tree=(r.large_trees||[]).find(t=>key(t.tile?.[0],t.tile?.[1])===ref.id);out.push({type:'tree',kind:'tile',data:{style,tree:clone(tree)},tx:ref.tile[0],ty:ref.tile[1]})}else if(ref.type==='blocker'){out.push({type:'blocker',kind:'tile',data:{style:clone(r.blocker_styles?.[ref.id]||{})},tx:ref.tile[0],ty:ref.tile[1]})}else if(ref.type==='water'||ref.type==='path')out.push({type:ref.type,kind:'tile',data:{},tx:ref.tile[0],ty:ref.tile[1]})}return out}
    copySelection(){if(!this.selection.length)return;const refs=this.selection.filter(s=>RelayEditorPolicy.allows(s,'copy')),data=this.copySelectionData(refs);if(!data.length){this.game.toast('Selection has no copyable editor items.',1.4);return}const xs=data.map(d=>d.kind==='pixel'?d.x:d.tx*TILE+TILE/2),ys=data.map(d=>d.kind==='pixel'?d.y:d.ty*TILE+TILE/2);this.clipboard={items:data,anchor:{x:Math.min(...xs),y:Math.min(...ys)},persistentRobotCopies:data.filter(c=>c.type==='robot'&&c.data?.id).length};this.game.toast(`Copied ${data.length} editor item${data.length===1?'':'s'}`,1.2);this.updateStatus()}
    pasteClipboard(){if(!this.clipboard?.items?.length)return;this.beginTransaction('paste');const ox=this.hover.x-this.clipboard.anchor.x,oy=this.hover.y-this.clipboard.anchor.y,tdx=Math.round(ox/TILE),tdy=Math.round(oy/TILE);this.selection=[];for(const c of this.clipboard.items)this.pasteDataItem(c,c.kind==='pixel'?ox:tdx,c.kind==='pixel'?oy:tdy,false);this.rebuildRoom();this.commitTransaction();const note=this.clipboard.persistentRobotCopies?' · Copied as decorative robot; persistent ID not duplicated.':'';this.game.toast(`Pasted ${this.clipboard.items.length} item${this.clipboard.items.length===1?'':'s'}${note}`,this.clipboard.persistentRobotCopies?2.4:1.1)}
    pasteDataItem(c,dx,dy,moving=false){const r=this.rawRoom();if(c.kind==='pixel'){const d=clone(c.data);d.x=clamp(Math.round((c.x+dx)*100)/100,0,W);d.y=clamp(Math.round((c.y+dy)*100)/100,0,PLAY_H);if(c.type==='decor'){d.editor_id=`decor_${this.nextDecorId++}`;r.editor_decor=r.editor_decor||[];r.editor_decor.push(d)}else{d.seed=moving?d.seed:((Number(d.seed)||Date.now())+this.nextDecorId*7919)>>>0;r.grass_clumps=r.grass_clumps||[];r.grass_clumps.push(d)}return}const tx=clamp(c.tx+dx,0,GRID_W-1),ty=clamp(c.ty+dy,0,GRID_H-1);if(c.type==='path'||c.type==='water')this.placeTile({kind:c.type},tx,ty);else if(c.type==='blocker'){this.placeTile({kind:'blocker',sprite:c.data.style?.sprite},tx,ty);r.blocker_styles[key(tx,ty)]={...c.data.style}}else if(c.type==='tree'){const sprite=c.data.tree?.sprite||c.data.style?.sprite;this.placeTile({kind:'tree',sprite},tx,ty);r.blocker_styles[key(tx,ty)]={...c.data.style,sprite:c.data.style?.sprite||sprite};const tree=(r.large_trees||[]).find(t=>t.tile?.[0]===tx&&t.tile?.[1]===ty);if(tree)tree.sprite=c.data.tree?.sprite||sprite}else if(c.type==='lamp'){const d=clone(c.data);d.tile=[tx,ty];this.replaceByTile(r.decor_lamps=r.decor_lamps||[],tx,ty,d)}else if(c.type==='robot'){const d=clone(c.data);d.tile=[tx,ty];if(!moving&&d.id)delete d.id;this.replaceByTile(r.decor_robots=r.decor_robots||[],tx,ty,d)}else if(c.type==='moth'){const d=clone(c.data);d.tile=[tx,ty];if(!moving)d.id=this.nextPersistentId('moth','editor_moth');(r.moth_pickups=r.moth_pickups||[]).push(d)}else if(c.type==='wildlife'){const d=clone(c.data);d.spawn=[tx,ty];if(!moving)d.id=this.nextPersistentId('wildlife',`editor_${d.kind||'wildlife'}`);(r.creature_groups=r.creature_groups||[]).push(d)}else if(c.type==='mini'){const d=clone(c.data);d.spawn=[tx,ty];if(!moving)d.id=this.nextPersistentId('mini',`editor_mini_${d.variant||'teal'}`);(r.mini_robot_groups=r.mini_robot_groups||[]).push(d)}}
    selectedObjective(){return this.selection.length===1&&this.selection[0].type==='objective'?this.selection[0]:null}
    toggleObjectiveVisual(){const ref=this.selectedObjective();if(!ref){this.game.toast('Select one objective in OBJECT mode.',1.5);return}const r=this.rawRoom(),hidden=new Set((r.object_fx_hidden||[]).map(String)),hide=!hidden.has(String(ref.id));this.beginTransaction(hide?'hide objective visual':'show objective visual');if(hide){r.object_fx_hidden=r.object_fx_hidden||[];if(!r.object_fx_hidden.includes(ref.id))r.object_fx_hidden.push(ref.id)}else r.object_fx_hidden=(r.object_fx_hidden||[]).filter(id=>String(id)!==String(ref.id));this.rebuildRoom();this.commitTransaction();this.game.toast(`Objective ${ref.id} visual ${hide?'hidden':'shown'} · gameplay unchanged`,1.8)}
    restoreSelectedSuppressed(){const ref=this.selection.length===1?this.selection[0]:null;if(!ref){this.game.toast('Select one suppressed item to restore.',1.5);return}const r=this.rawRoom();this.beginTransaction('restore suppressed item');let changed=false;if(ref.type==='suppressed-procedural'||ref.type==='suppressed-decor-tile')changed=RelayProceduralDecor.restore(r,ref.obj||ref.tile);else if(ref.type==='suppressed-pattern'){const before=(r.pattern_exclusions||[]).length;r.pattern_exclusions=(r.pattern_exclusions||[]).filter(id=>String(id)!==String(ref.id));changed=r.pattern_exclusions.length!==before}else if(ref.type==='objective'&&ref.hiddenVisual){const before=(r.object_fx_hidden||[]).length;r.object_fx_hidden=(r.object_fx_hidden||[]).filter(id=>String(id)!==String(ref.id));changed=r.object_fx_hidden.length!==before}if(!changed){this.cancelTransaction(false);this.game.toast('Selected item is not suppressed.',1.4);return}this.selection=[];this.rebuildRoom();this.commitTransaction();this.game.toast('Suppressed item restored.',1.3)}
    convertProceduralSelection(){const ref=this.selection.length===1?this.selection[0]:null;if(!ref||ref.type!=='procedural-decor'){this.game.toast('Select one active generated decoration to convert.',1.6);return}const d=ref.obj,r=this.rawRoom(),editorId=`decor_${this.nextDecorId++}`;this.beginTransaction('convert procedural decor');RelayProceduralDecor.suppress(r,d);r.editor_decor=r.editor_decor||[];r.editor_decor.push({editor_id:editorId,x:d.x,y:d.y,sprite:d.sprite,scale:d.scale??1,alpha:d.alpha??1,flip:!!d.flip,rot:0,element:d.element,tint_index:d.tintIndex??156,tint_strength:d.tintStrength,glow:d.glow?{dx:d.glow.x-d.x,dy:d.glow.y-d.y,element:d.glow.element,index:d.glow.index,radius:d.glow.radius,alpha:d.glow.alpha}:undefined});this.selection=[];this.rebuildRoom();const created=this.collectItems().find(it=>it.type==='decor'&&it.id===editorId);this.selection=created?[created]:[];this.commitTransaction();this.renderOverlay();this.updateStatus();this.game.toast('Generated decor converted to authored; original suppressed.',1.8)}
    updateActionButtons(){const objective=this.selectedObjective(),hidden=!!objective?.hiddenVisual,restore=this.selection.length===1&&(this.selection[0].type==='suppressed-procedural'||this.selection[0].type==='suppressed-decor-tile'||this.selection[0].type==='suppressed-pattern'||(objective&&hidden)),convert=this.selection.length===1&&this.selection[0].type==='procedural-decor',visual=root.document?.querySelector?.('#editorObjectiveVisual'),restoreBtn=root.document?.querySelector?.('#editorRestoreSuppressed'),convertBtn=root.document?.querySelector?.('#editorConvertProcedural');if(visual){visual.disabled=!objective;visual.textContent=hidden?'SHOW VISUAL':'HIDE VISUAL'}if(restoreBtn)restoreBtn.disabled=!restore;if(convertBtn)convertBtn.disabled=!convert}
    updateStatus(){this.updateActionButtons();if(!this.status)return;const h=this.historyFor();this.status.textContent=`${this.roomKey()} · ${this.tool.toUpperCase()} · ${this.choice?.label||''} · selected ${this.selection.length} · undo ${h.undo.length} · redo ${h.redo.length}${this.showSuppressed?' · SUPPRESSED VISIBLE':''}${this.clipboard?` · clipboard ${this.clipboard.items.length}`:''}`}
    selectionKeys(){return [...new Map(this.selection.map(ref=>[`${ref.type}\u0000${ref.id}`,{type:ref.type,id:ref.id}])).values()]}
    refreshSelection(keys){if(!keys?.length){this.selection=[];return}const items=this.collectItems();this.selection=keys.map(k=>items.find(it=>it.type===k.type&&it.id===k.id)).filter(Boolean)}
    rebuildRoom(){const selected=this.selectionKeys(),idx=this.game.state.room,spec=this.game.storyData.rooms[idx],old=this.game.room;this.game.rooms[idx]=new Room(idx,spec,this.game.maps);this.game.room=this.game.rooms[idx];this.game.room.bridgeProgress=old?.bridgeProgress||0;this.game.room.bridgeBuilt=old?.bridgeBuilt||false;if(!this.game.room.walkablePixel(this.game.x,this.game.y,PLAYER_COLLISION_R)){const t=this.game.room.nearestClearWalkable(this.game.room.tile(this.game.x,this.game.y),PLAYER_COLLISION_R);[this.game.x,this.game.y]=this.game.room.center(t)}this.game.bgKey='';this.game.ensureBackground(true);this.game.creatures?.init(this.game.room);this.game.miniGuides?.init(this.game.room,this.game.state);this.refreshSelection(selected);this.renderOverlay();this.updateStatus()}
    ghostGeometry(e){const centred=['moth','wildlife','mini'].includes(e.kind);let scale=e.scale??1;if(e.kind==='robot')scale=.84;else if(e.kind==='lamp')scale=.66;else if(e.kind==='moth')scale=.36;else if(e.kind==='mini')scale=1.52;else if(e.kind==='wildlife')scale=['pixie','mushroom_pixie'].includes(e.wildlifeKind)?1.62:1.755;if(!centred)scale=this.game.painter.spriteScale(e.sprite,scale);return{scale,anchor:centred?'center':'bottom',alpha:.56*(e.alpha??1)}}
    drawSpriteGhost(ctx,e,x,y,alpha=.56){if(!e?.sprite||!this.game.art.regions[e.sprite])return;const geometry=this.ghostGeometry(e);this.game.art.draw(ctx,e.sprite,x,y,null,null,{...geometry,alpha:alpha*(e.alpha??1),flip:!!e.flip,rot:Number(e.rot)||0})}
    drawLampGhost(ctx,e,x,y){this.drawSpriteGhost(ctx,{kind:'decor',sprite:'orb_pillar',scale:.92},x,y+11);this.drawSpriteGhost(ctx,e,x,y-18)}
    renderOverlay(){if(!this.overlay)return;const c=this.ctx;c.clearRect(0,0,W,H);if(!this.active)return;if(this.showGrid){c.save();c.strokeStyle='#6ff4dd28';c.lineWidth=1;for(let x=0;x<=W;x+=TILE){c.beginPath();c.moveTo(x+.5,0);c.lineTo(x+.5,PLAY_H);c.stroke()}for(let y=0;y<=PLAY_H;y+=TILE){c.beginPath();c.moveTo(0,y+.5);c.lineTo(W,y+.5);c.stroke()}c.restore()}
      if(this.tool==='object'){c.save();c.font='7px "Cascadia Mono",Consolas,monospace';c.textBaseline='bottom';for(const it of this.collectItems().filter(x=>x.layer==='gameplay')){const selected=this.selection.some(s=>this.sameRef(s,it)),hidden=it.type==='objective'&&it.hiddenVisual;c.strokeStyle=hidden?'#ff91d8cc':selected?'#ffe970cc':'#75f6ff66';c.fillStyle=hidden?'#ffc1e8':selected?'#ffe970':'#a8ffffbb';c.lineWidth=selected?1.5:1;c.setLineDash(hidden?[2,2]:[3,3]);const w=it.bbox.x1-it.bbox.x0,h=it.bbox.y1-it.bbox.y0;c.strokeRect(it.bbox.x0+.5,it.bbox.y0+.5,w-1,h-1);if(hidden){const [x,y]=this.game.room.center(it.tile),sprite=this.game.art.roles.objective?.[it.obj?.kind]||'orb_cyan';if(this.game.art.regions[sprite])this.game.art.draw(c,sprite,x,y+10,null,null,{anchor:'bottom',alpha:.28,scale:1})}const label=it.type==='objective'?`OBJ ${it.id}${hidden?' [VISUAL HIDDEN]':''}`:it.type==='wildlife'?`${it.obj?.kind||'wildlife'} ×${it.obj?.count||1}`:it.type==='moth'?`MOTH ${it.obj?.id||''}`:it.type==='mini'?`MINI ${it.obj?.variant||''}`:it.type;c.fillText(label,it.bbox.x0+2,Math.max(9,it.bbox.y0-1))}c.restore()}
      if(this.showSuppressed){c.save();c.font='7px "Cascadia Mono",Consolas,monospace';c.textBaseline='top';for(const it of this.collectItems().filter(x=>x.suppressed||x.type.startsWith('suppressed-'))){c.strokeStyle='#ff83d5dd';c.fillStyle='#ff9bdd22';c.lineWidth=1.2;c.setLineDash([2,2]);const w=it.bbox.x1-it.bbox.x0,h=it.bbox.y1-it.bbox.y0;c.fillRect(it.bbox.x0,it.bbox.y0,w,h);c.strokeRect(it.bbox.x0+.5,it.bbox.y0+.5,w-1,h-1);if(it.type==='suppressed-procedural'&&it.obj?.sprite)this.drawSpriteGhost(c,{...it.obj,kind:'decor'},it.obj.x,it.obj.y,.22);else if(it.type==='suppressed-pattern'&&it.obj?.sprite&&this.game.art.regions[it.obj.sprite]){const x=(it.bbox.x0+it.bbox.x1)/2,y=(it.bbox.y0+it.bbox.y1)/2;this.game.art.draw(c,it.obj.sprite,x,y,null,null,{anchor:'center',scale:it.obj.scale??1,alpha:.22})}const label=it.type==='suppressed-pattern'?`SUPPRESSED ${it.obj?.label||it.id}`:it.type==='suppressed-procedural'?`SUPPRESSED ${it.obj?.sprite||it.id}`:`DECOR EXCLUSION ${it.tile?.join(',')||it.id}`;c.fillStyle='#ffc1e8';c.fillText(label,it.bbox.x0+2,it.bbox.y0+2)}c.restore()}
      for(const s of this.selection){c.save();c.strokeStyle='#ffe970';c.fillStyle='#ffe97018';c.lineWidth=1.8;c.setLineDash([5,3]);c.fillRect(s.bbox.x0,s.bbox.y0,s.bbox.x1-s.bbox.x0,s.bbox.y1-s.bbox.y0);c.strokeRect(s.bbox.x0+.5,s.bbox.y0+.5,s.bbox.x1-s.bbox.x0-1,s.bbox.y1-s.bbox.y0-1);c.restore()}
      if((this.dragMode==='selectBox'||this.dragMode==='objectSelectBox')&&this.dragStart&&this.dragNow){const r=rectFrom(this.dragStart,this.dragNow);c.save();c.strokeStyle='#95ffff';c.fillStyle='#5be7ff18';c.setLineDash([4,3]);c.strokeRect(r.x0,r.y0,r.x1-r.x0,r.y1-r.y0);c.fillRect(r.x0,r.y0,r.x1-r.x0,r.y1-r.y0);c.restore()}
      if(this.dragMode==='move'&&this.dragStart&&this.dragNow){const dx=this.dragNow.x-this.dragStart.x,dy=this.dragNow.y-this.dragStart.y;c.save();c.strokeStyle='#ff9ce2';c.setLineDash([3,3]);for(const s of this.selection)c.strokeRect(s.bbox.x0+dx,s.bbox.y0+dy,s.bbox.x1-s.bbox.x0,s.bbox.y1-s.bbox.y0);c.restore()}
      if(!this.pointerDown&&this.tool==='brush'&&this.choice){const [tx,ty]=this.tileAt(this.hover),x=tx*TILE+TILE/2,y=ty*TILE+TILE;if(['path','water','solid','clear','blocker','tree'].includes(this.choice.kind)){c.save();c.fillStyle=this.choice.kind==='water'?'#42c7ff38':this.choice.kind==='path'?'#ffd17b35':'#bbff9c25';c.strokeStyle='#eaffffaa';c.fillRect(tx*TILE,ty*TILE,TILE,TILE);c.strokeRect(tx*TILE+.5,ty*TILE+.5,TILE-1,TILE-1);c.restore();if(this.choice.sprite)this.drawSpriteGhost(c,this.choice,x,y+2)}else if(this.choice.kind==='grass'){c.save();c.strokeStyle='#75ffb8bb';c.fillStyle='#58de8e24';c.beginPath();c.ellipse(this.hover.x,this.hover.y,this.choice.radius,this.choice.radius*.7,0,0,Math.PI*2);c.fill();c.stroke();c.restore()}else if(this.choice.kind==='decor')this.drawSpriteGhost(c,this.choice,this.hover.x,this.hover.y);else if(this.choice.kind==='lamp')this.drawLampGhost(c,this.choice,tx*TILE+TILE/2,ty*TILE+TILE/2);else if(this.choice.kind==='robot')this.drawSpriteGhost(c,this.choice,tx*TILE+TILE/2,ty*TILE+TILE/2+10);else if(['moth','wildlife','mini'].includes(this.choice.kind))this.drawSpriteGhost(c,this.choice,tx*TILE+TILE/2,ty*TILE+TILE/2);else if(this.choice.kind==='ambient')this.drawSpriteGhost(c,this.choice,this.hover.x,this.hover.y)}
    }
    async saveProject(){try{const res=await fetch('/__editor/save_maps',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(this.game.maps,null,2)+'\n'});if(!res.ok)throw new Error((await res.text())||`HTTP ${res.status}`);const data=await res.json();this.game.toast(`Saved relay_moth_maps.json · backup ${data.backup||'created'}`,2)}catch(e){this.game.toast('Project save unavailable · use Download JSON · '+e.message,3)}}
    downloadMaps(){download('relay_moth_maps.json',JSON.stringify(this.game.maps,null,2)+'\n');this.game.toast('Map JSON downloaded',1.2)}
  }

  root.WysiwygEditor=WysiwygEditor;
  root.setupWysiwygEditor=function(game){if(root.rmfEditor)return root.rmfEditor;root.rmfEditor=new WysiwygEditor(game);return root.rmfEditor};
  root.toggleWysiwygEditor=function(){root.rmfEditor?.toggle()};
})(typeof globalThis!=='undefined'?globalThis:window);
